# 02. Data Cleaning

## Objective

The data cleaning stage aims to ensure the Employee Attrition dataset is of high quality before being used in the Exploratory Data Analysis (EDA) and Statistical Analysis stages.

The cleaning process includes:

1. Checking the dataset structure and quality.
2. Identifying duplicate data.
3. Identifying missing values.
4. Checking for data type inconsistencies.
5. Identifying invalid or inconsistent values.
6. Handling duplicate data and missing values if found.
7. Validating the Attrition target variable.
8. Saving the cleaned dataset.

The output of this notebook is a cleaned dataset that will serve as input for the next stage.

## Import Library

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

## Load Dataset

In [2]:
DATA_PATH = Path("../data/raw/employee_attrition.csv")

data = pd.read_csv(DATA_PATH)

data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,MonthlyIncomeBracket,OverallSatisfactionIndex
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,35-44,Established (6-10 yrs),High,2.00
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45-54,Established (6-10 yrs),High,3.00
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,35-44,New (0-2 yrs),Low,3.00
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-34,Established (6-10 yrs),Low,3.25
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-34,New (0-2 yrs),Medium,2.50

In [3]:
data.shape

(1470, 39)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
 35  AgeGroup                  1470 non-null   object
 36  TenureGroup               1470 non-null   object
 37  MonthlyIncomeBracket      1470 non-null   object
 38  OverallSatisfactionIndex  1470 non-null   float64
dtypes: float64(1), int64(26), object(12)
memory usage: 448.0+ KB

In [5]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,MonthlyIncomeBracket,OverallSatisfactionIndex
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,35-44,Established (6-10 yrs),High,2.00
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45-54,Established (6-10 yrs),High,3.00
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,35-44,New (0-2 yrs),Low,3.00
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-34,Established (6-10 yrs),Low,3.25
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-34,New (0-2 yrs),Medium,2.50

In [6]:
data.sample(5, random_state=42)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,MonthlyIncomeBracket,OverallSatisfactionIndex
1041,28,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,Sales Executive,1,Single,8463,23490,0,Y,No,18,3,4,80,0,6,4,3,5,4,1,3,25-34,Early (3-5 yrs),Very High,3.00
184,53,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,Manufacturing Director,1,Divorced,4450,26250,1,Y,No,11,3,3,80,2,5,3,3,4,2,1,3,45-54,Early (3-5 yrs),Medium,2.75
1222,24,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,Human Resources,3,Married,1555,11585,1,Y,No,11,3,3,80,1,1,2,3,1,0,0,0,Under 25,New (0-2 yrs),Low,3.25
67,45,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,Research Scientist,1,Divorced,9724,18787,2,Y,No,17,3,3,80,1,25,2,3,1,0,0,0,45-54,New (0-2 yrs),Very High,2.25
220,36,No,Travel_Rarely,1396,Research & Development,5,2,Life Sciences,1,304,4,Male,62,3,2,Laboratory Technician,2,Single,5914,9945,8,Y,No,16,3,4,80,0,16,3,4,13,11,3,7,35-44,Veteran (10+ yrs),High,3.50

## Duplicate Data

In [30]:
print("Duplicate before drop:", data.duplicated().sum())

Duplicate before drop: 0

In [8]:
duplicates = data[data.duplicated(keep=False)]

duplicates.head()

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager, AgeGroup, TenureGroup, MonthlyIncomeBracket, OverallSatisfactionIndex]
Index: []

In [12]:
data = data.drop_duplicates()

In [29]:
print("Duplicate after drop:", data.duplicated().sum())

Duplicate after drop: 0

## Missing Values

In [17]:
missing_values = (
    data.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_values

Age                         0
TrainingTimesLastYear       0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
WorkLifeBalance             0
NumCompaniesWorked          0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
AgeGroup                    0
TenureGroup                 0
MonthlyIncomeBracket        0
Over18                      0
MonthlyRate                 0
Attrition                   0
EmployeeNumber              0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EnvironmentSatisfaction     0
MonthlyIncome               0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
OverallSatisfactionIndex    0
dtype: int64

Fill numeric datawith the median.

Fill in categorical data with the mode.

In [32]:
numeric_missing = [
    col for col in numeric_columns
    if data[col].isnull().sum() > 0
]

for column in numeric_missing:
    data[column] = data[column].fillna(
        data[column].median()
    )
numeric_missing

[]

In [33]:
categorical_missing = [
    col for col in categorical_columns
    if data[col].isnull().sum() > 0
]

for column in categorical_missing:
    data[column] = data[column].fillna(
        data[column].mode()[0]
    )
categorical_missing

[]

## Data Types

In [20]:
dtype = pd.DataFrame({
    "dtype": data.dtypes
})

dtype

                            dtype
Age                         int64
Attrition                  object
BusinessTravel             object
DailyRate                   int64
Department                 object
DistanceFromHome            int64
Education                   int64
EducationField             object
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                     object
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                    object
JobSatisfaction             int64
MaritalStatus              object
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                     object
OverTime                   object
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
AgeGroup                   object
TenureGroup                object
MonthlyIncomeBracket       object
OverallSatisfactionIndex  float64

In [22]:
categorical_columns = data.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numeric_columns = data.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Categorical columns:")
print(categorical_columns)

print("\nNumeric columns:")
print(numeric_columns)

Categorical columns:
['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime', 'AgeGroup', 'TenureGroup', 'MonthlyIncomeBracket']

Numeric columns:
['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'OverallSatisfactionIndex']

## Unique Values

In [23]:
for column in categorical_columns:
    print(f"\n{'='*50}")
    print(f"Column: {column}")
    print(f"{'='*50}")
    print(data[column].value_counts(dropna=False).head(20))

==================================================
Column: Attrition
==================================================
Attrition
No     1233
Yes     237
Name: count, dtype: int64

==================================================
Column: BusinessTravel
==================================================
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

==================================================
Column: Department
==================================================
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

==================================================
Column: EducationField
==================================================
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

==================================================
Column: Gender
==================================================
Gender
Male      882
Female    588
Name: count, dtype: int64

==================================================
Column: JobRole
==================================================
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

==================================================
Column: MaritalStatus
==================================================
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

==================================================
Column: Over18
==================================================
Over18
Y    1470
Name: count, dtype: int64

==================================================
Column: OverTime
==================================================
OverTime
No     1054
Yes     416
Name: count, dtype: int64

==================================================
Column: AgeGroup
==================================================
AgeGroup
25-34       554
35-44       505
45-54       245
Under 25     97
55+          69
Name: count, dtype: int64

==================================================
Column: TenureGroup
==================================================
TenureGroup
Established (6-10 yrs)    448
Early (3-5 yrs)           434
New (0-2 yrs)             342
Veteran (10+ yrs)         246
Name: count, dtype: int64

==================================================
Column: MonthlyIncomeBracket
==================================================
MonthlyIncomeBracket
Low          369
Very High    368
High         367
Medium       366
Name: count, dtype: int64

In [24]:
print(data["Attrition"].value_counts())

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [25]:
print(data["BusinessTravel"].value_counts())

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

## Invalid Values

In [26]:
data[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.00,36.00,43.00,60.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.00,802.00,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.00,7.00,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.00,3.00,4.00,5.0
EmployeeCount,1470.0,1.000000,0.000000,1.0,1.00,1.00,1.00,1.0
EmployeeNumber,1470.0,1024.865306,602.024335,1.0,491.25,1020.50,1555.75,2068.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.00,3.00,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.00,66.00,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.00,3.00,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.00,2.00,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.00,3.00,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.00,4919.00,8379.00,19999.0
MonthlyRate,1470.0,14313.103401,7117.786044,2094.0,8047.00,14235.50,20461.50,26999.0
NumCompaniesWorked,1470.0,2.693197,2.498009,0.0,1.00,2.00,4.00,9.0
PercentSalaryHike,1470.0,15.209524,3.659938,11.0,12.00,14.00,18.00,25.0
PerformanceRating,1470.0,3.153741,0.360824,3.0,3.00,3.00,3.00,4.0
RelationshipSatisfaction,1470.0,2.712245,1.081209,1.0,2.00,3.00,4.00,4.0
StandardHours,1470.0,80.000000,0.000000,80.0,80.00,80.00,80.00,80.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.00,1.00,1.00,3.0
TotalWorkingYears,1470.0,11.279592,7.780782,0.0,6.00,10.00,15.00,40.0
TrainingTimesLastYear,1470.0,2.799320,1.289271,0.0,2.00,3.00,3.00,6.0
WorkLifeBalance,1470.0,2.761224,0.706476,1.0,2.00,3.00,3.00,4.0
YearsAtCompany,1470.0,7.008163,6.126525,0.0,3.00,5.00,9.00,40.0
YearsInCurrentRole,1470.0,4.229252,3.623137,0.0,2.00,3.00,7.00,18.0
YearsSinceLastPromotion,1470.0,2.187755,3.222430,0.0,0.00,1.00,3.00,15.0
YearsWithCurrManager,1470.0,4.123129,3.568136,0.0,2.00,3.00,7.00,17.0
OverallSatisfactionIndex,1470.0,2.730952,0.505815,1.0,2.50,2.75,3.00,4.0

In [27]:
negative_values = {}

for column in numeric_columns:
    count = (data[column] < 0).sum()
    
    if count > 0:
        negative_values[column] = count

negative_values

{}

There are no negative values in the numerical features.

## Zero Values

In [28]:
zero_summary = pd.DataFrame({
    "zero_count": (data[numeric_columns] == 0).sum(),
})

zero_summary = zero_summary.sort_values(
    "zero_count",
    ascending=False
)

zero_summary

                          zero_count
StockOptionLevel                 631
YearsSinceLastPromotion          581
YearsWithCurrManager             263
YearsInCurrentRole               244
NumCompaniesWorked               197
TrainingTimesLastYear             54
YearsAtCompany                    44
TotalWorkingYears                 11
PercentSalaryHike                  0
WorkLifeBalance                    0
StandardHours                      0
RelationshipSatisfaction           0
PerformanceRating                  0
Age                                0
DailyRate                          0
MonthlyRate                        0
MonthlyIncome                      0
JobSatisfaction                    0
JobLevel                           0
JobInvolvement                     0
HourlyRate                         0
EnvironmentSatisfaction            0
EmployeeNumber                     0
EmployeeCount                      0
Education                          0
DistanceFromHome                   0
OverallSatisfactionIndex           0

## Inconsistent Values

In [35]:
for column in categorical_columns:
    data[column] = data[column].astype(str).str.strip()

In [36]:
for column in categorical_columns:
    print(f"\n{column}")
    print(data[column].unique())

Attrition
['Yes' 'No']

BusinessTravel
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

Department
['Sales' 'Research & Development' 'Human Resources']

EducationField
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

Gender
['Female' 'Male']

JobRole
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

MaritalStatus
['Single' 'Married' 'Divorced']

Over18
['Y']

OverTime
['Yes' 'No']

AgeGroup
['35-44' '45-54' '25-34' '55+' 'Under 25']

TenureGroup
['Established (6-10 yrs)' 'New (0-2 yrs)' 'Early (3-5 yrs)'
 'Veteran (10+ yrs)']

MonthlyIncomeBracket
['High' 'Low' 'Medium' 'Very High']

## Target Value Validation

In [38]:
TARGET = "Attrition"

print(data[TARGET].value_counts(dropna=False))

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [39]:
attrition_distribution = pd.DataFrame({
    "count": data[TARGET].value_counts(),
    "percentage": data[TARGET].value_counts(normalize=True) * 100
})

attrition_distribution

           count  percentage
Attrition
No          1233   83.877551
Yes          237   16.122449

In [40]:
valid_attrition = {"Yes", "No"}

invalid_attrition = set(data[TARGET].dropna().unique()) - valid_attrition

print("Invalid Attrition values:")
print(invalid_attrition)

Invalid Attrition values:
set()

## Check ID / Identifier Columns

In [41]:
id_like_columns = [
    column for column in data.columns
    if "id" in column.lower()
    or "number" in column.lower()
]

print(id_like_columns)

['EmployeeNumber']

## Final Quality Report

In [42]:
quality_report = pd.DataFrame({
    "Metric": [
        "Number of Rows",
        "Number of Columns",
        "Duplicate Rows",
        "Missing Values",
        "Numeric Features",
        "Categorical Features",
        "Target Variable"
    ],
    
    "Value": [
        data.shape[0],
        data.shape[1],
        data.duplicated().sum(),
        data.isnull().sum().sum(),
        len(numeric_columns),
        len(categorical_columns),
        TARGET
    ]
})

quality_report

                 Metric      Value
0        Number of Rows       1470
1     Number of Columns         39
2        Duplicate Rows          0
3        Missing Values          0
4      Numeric Features         27
5  Categorical Features         12
6       Target Variable  Attrition

## Save Clean Dataset

In [45]:
OUTPUT_PATH = Path(
    "../data/clean/clean_employee_attrition.csv"
)

OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

data.to_csv(
    OUTPUT_PATH,
    index=False
)

print(f"Clean dataset saved to: {OUTPUT_PATH}")

Clean dataset saved to: ..\data\clean\clean_employee_attrition.csv

## Verify Saved Dataset

In [46]:
clean_data = pd.read_csv(OUTPUT_PATH)

print("Shape:", clean_data.shape)

clean_data.head()

Shape: (1470, 39)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,TenureGroup,MonthlyIncomeBracket,OverallSatisfactionIndex
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5,35-44,Established (6-10 yrs),High,2.00
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7,45-54,Established (6-10 yrs),High,3.00
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0,35-44,New (0-2 yrs),Low,3.00
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0,25-34,Established (6-10 yrs),Low,3.25
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2,25-34,New (0-2 yrs),Medium,2.50